### ISSUE TITLE
Question: Preferred way to instantiate injector

### ISSUE THREAD

**Issue by asyncee** [alecthomas/injector#103]
Hello, i have a question about what is the best practices to instantiate injector.

Currently there are two ways in my mind:

```python
def setup_injector(config):
     # Use a closure to configure injector with dynamically passed config.
     def setup_configuration(binder):
          binder.bind(Config, to=config)
  
     return Injector([setup_configuration, Module1(), Module2(), ... ])
```

That way all injector-specific initialization code is tied to it and is hidden from the client. The client code then just calls `injector = setup_injector(config=ProductionConfig())`.

The downside of this approach i see is that injector is created dynamically on the most outer (higher) layer of code, where the application is created, so it can not be imported by underlying code (to keep dependency graph between modules oneway and to follow clean architecture dependency rule).

Injector factory function allows to create injector with specific configuration passed (Config instance).

This is my current approach. The code is:

```python
# Application.containers contains all providers and injector factory
from application.containers import setup_injector

config = get_config_from_command_line_arguments()

# It is forbidden to import injector in other places of a program
# to avoid circular import errors.
injector = setup_injector(config=config)
main = injector.get(Main)
main.run()
```

The second approach i see is to create a singleton of injector by calling `injector = Injector()` on module level. This will create an application-global (and importable) constant. So the `injector` instance can be imported anywhere in the program. This will allow following code work:

```
# application.database module

from application.containers import injector          

def transactional(fn):
     def wrapper(*args, **kwargs):
          session = injector.get(Session)
          fn(*args, **kwargs)
          session.commit()
```

But this approach has it's downside — i can not get my head around how to **dynamically** configure this global instance of injector with different configuration, say a development config.

My application is configured via command line arguments and not environment variables.

Thanks!

**Comment by jstasiak** [comment]
The first way (creating a non-global, non-module-level `Injector` in the outermost layer of the application) is definitely the way to go. It's possible, that the global variable approach may be preferable in some situation, but it's highly unlikely and I consider it an antipattern. If you can import configured `Injector` in any function down the call stack you can subvert the whole dependency injection no global state thing. :)

There's a way to do decorators without module-level (I should probably document that somewhere), it requires that the function being decorated is already called using `Injector`, see:

```python
import functools

from injector import Injector, inject, singleton


@singleton
class Session:
    def thingy(self):
        print('thingy')

    def commit(self):
        print('committing')


def transactional(function):
    # session named with some fancy decorations to avoid clashing with any kwarg
    # that the function being wrapped may have
    @functools.wraps(function)
    def wrapper(*args, __transactional_session__, **kwargs):
        function(*args, **kwargs)
        __transactional_session__.commit()

    # This is to tell Injector that we want something extra
    original_annotations = getattr(wrapper, '__annotations__', {})
    wrapper.__annotations__ = {**original_annotations, '__transactional_session__': Session}

    return wrapper


@inject
@transactional
def do_things(session: Session):
    print('a')
    session.thingy()
    print('b')


if __name__ == '__main__':
    injector = Injector()
    injector.call_with_injection(do_things)
```

Due to the limitations of how it works you can't decorate plain "innocent" functions with it:

```
@transactional
def fun():
    print('Oh hi')


# ...

# This won't work
fun()
```

I don't think it should work anyway, so I think it's fine.

**Comment by asyncee** [comment]
Thank you very much!

When i tried such approach i missed that the called function must be decorated with `@inject`. It would be great to have a doc (or a link to this issue maybe) available.
