### ISSUE TITLE
Document __slots__ behavior

### ISSUE THREAD

**Issue by masell** [alecthomas/injector#106]
When using `__slots__` it should be documented that a `__injector__` slot is required.

https://github.com/alecthomas/injector/blob/master/injector.py#L756

Instead of `Can\'t create an instance of type %r due to presence of __slots__,  remove __slots__ to fix that'`

It should say:
`Can\'t create an instance of type %r due to presence of __slots__ and no __injector__ slot defined, remove __slots__ or add __injector__ to __slots__ to fix that`

**Comment by jstasiak** [comment]
This is no longer necessary since dcbd8c42bfab262a83c5c3b73afcf968c0b865d5 (Injector 0.16.0+) has been introduced.
