### ISSUE TITLE
Injecting in a subclass

### ISSUE THREAD

**Issue by pohmelie** [alecthomas/injector#112]
Recent update (v0.16.x) broke our code. So I decide to make this issue to clear the situation, is it a bug/feature/changed behavior or our improper usage of injector? Here is example of code we have:
``` python
import injector


class X:
    pass


class Y:
    pass


class A:
    @injector.inject
    def __init__(self, x: X):
        print(x)


class B(A):
    @injector.inject
    def __init__(self, y: Y):
        super().__init__()
        print(y)


injector = injector.Injector()
injector.binder.bind(X, X())
injector.binder.bind(Y, Y())
b = injector.create_object(B)
print(b)
```
For version 0.15.0 output is:
```
<__main__.X object at 0x7f129f08e630>
<__main__.Y object at 0x7f129f08e6a0>
<__main__.B object at 0x7f129f09f198>
```
For version 0.16.x output is:
```
Traceback (most recent call last):
  File "test-injector.py", line 28, in <module>
    b = injector.create_object(B)
  File "/home/broomrider/.pyenv/versions/3.6.5/lib/python3.6/site-packages/injector/__init__.py", line 735, in create_object
    self._stack,
  File "/home/broomrider/.pyenv/versions/3.6.5/lib/python3.6/site-packages/injector/__init__.py", line 72, in reraise
    raise exception.with_traceback(tb)
  File "/home/broomrider/.pyenv/versions/3.6.5/lib/python3.6/site-packages/injector/__init__.py", line 723, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/broomrider/.pyenv/versions/3.6.5/lib/python3.6/site-packages/injector/__init__.py", line 786, in call_with_injection
    reraise(e, CallError(self_, callable, args, dependencies, e, self._stack))
  File "/home/broomrider/.pyenv/versions/3.6.5/lib/python3.6/site-packages/injector/__init__.py", line 72, in reraise
    raise exception.with_traceback(tb)
  File "/home/broomrider/.pyenv/versions/3.6.5/lib/python3.6/site-packages/injector/__init__.py", line 784, in call_with_injection
    return callable(*full_args, **dependencies)
  File "test-injector.py", line 21, in __init__
    super().__init__()
TypeError: __init__() missing 1 required positional argument: 'x'
```

`injector.call_with_injection(super().__init__)` solves the problem, but I want to know what is the official™ way to inject to parent constructor and if it is a proper way, then why it works before?

**Comment by jstasiak** [comment]
First of all – I'm sorry I broke your code.

This is an unfortunate (although predictable) consequence of https://github.com/alecthomas/injector/commit/dcbd8c42bfab262a83c5c3b73afcf968c0b865d5 (mentioned in [the changelog](https://injector.readthedocs.io/en/latest/changelog.html)). I don't think injecting into parent/super constructors was ever officially supported but it did work thanks to some implementation details removed by the commit I mention. I thought about it for a while and all inheritance-based use cases I could think about could be solved by composition instead, for example:

```python
import injector

class X:
    pass


class Y:
    pass


class A:
    @injector.inject
    def __init__(self, x: X):
        print(x)


class B:
    @injector.inject
    def __init__(self, a: A, y: Y):
        print(y)


injector = injector.Injector()
injector.binder.bind(X, X())
injector.binder.bind(Y, Y())
b = injector.create_object(B)
print(b)
```

so I went ahead with it.

I see the following possible solutions to the problem:
* Stick with Injector 0.15.x
* Replace inheritance with composition
* Inject Injector and use `Injector.call_with_injection()`
* Bring back injecting into parent constructors *without* the method wrapper thingy removed in https://github.com/alecthomas/injector/commit/dcbd8c42bfab262a83c5c3b73afcf968c0b865d5 – this is a hypothetical internal solution, not sure how plausible)

**Comment by jstasiak** [comment]
Ugh, I'm sorry, I *thought* I mentioned this in the changelog but I didn't, I need to fix that.

**Comment by pohmelie** [comment]
Oh, I see. Thanks for fast response. I think we will refactor our code in some way instead of pin injector version.

**Comment by jonjrodriguez** [comment]
Just coming across this. I think the normal expectation would be that parent injection just works. Hopefully you can bring back official support for this.

**Comment by jstasiak** [comment]
If someone came up with a good solution bringing this behavior back and satisfying (quoting https://github.com/alecthomas/injector/issues/112#issuecomment-487718494)

> Bring back injecting into parent constructors without the method wrapper thingy removed in dcbd8c4 – this is a hypothetical internal solution, not sure how plausible)

I'd consider merging it, but I'm not particularly fond of calling `super()` in child class' constructor and having dependencies "magically" appear in the parent class' constructor so I'm torn here.

**Comment by mwgamble** [comment]
I've been testing the upgrade path from 0.15 to 0.17 recently myself, and found that it's also broken situations that involve multiple inheritance. For example:

```python
import injector

class A(object):
    pass

class B(object):
    pass

class C(object):
    pass

class M(object):
    @injector.inject
    def __init__(self, a: A):
        self.a = a

class N(M):
    @injector.inject
    def __init__(self, b: B, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.b = b

class O(M):
    @injector.inject
    def __init__(self, c: C, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.c = c

class P(O, N):
    pass

injector = injector.Injector()
injector.binder.bind(A, A())
injector.binder.bind(B, B())
injector.binder.bind(C, C())
o = injector.create_object(O)
```

In 0.15, this worked fine. In 0.16+, this no longer works - the interpreter complains that `b` hasn't been supplied to the constructor of `N`.
