### ISSUE TITLE
Can't get multibind to work

### ISSUE THREAD

**Issue by benwainwright** [alecthomas/injector#113]
Hi there. I've just spent several hours trying to get multibinding to work to no avail. I'm creating an injector module that collects all the modules in a given package and injects them as a multibind. The approach is this:

```python
class ApplicationInjectorModule(Module):

    def configure(self, binder: Binder):
        handlers = [
            getattr(application.handlers, class_name)
            for class_name in application.handlers.__all__
        ]

        for handler in handlers:
            binder.multibind(interface=[Handler], to=handler)
```

When I install this module and attempt to get an object that requires the handlers multibind, I'm getting an error thrown: `TypeError: '(type)' object is not iterable` (type) is one of the handler classes I'm trying to instantiate.

Any suggestions?

**Comment by benwainwright** [comment]
I originally tried binding it to a list of classes, but then it treats it like an instance binding and doesn't instantiate it

**Comment by alecthomas** [comment]
[This test](https://github.com/alecthomas/injector/blob/master/injector_test.py#L616-L622) seems closest to what you want. Is that sufficient?

**Comment by jstasiak** [comment]
Heads up – I'm in the process of improving the multibind API right now, after I'm done with it it should be possible to do the following:

```python
class ApplicationInjectorModule(Module):

    def configure(self, binder: Binder):
        handlers = [
            getattr(application.handlers, class_name)
            for class_name in application.handlers.__all__
        ]

        for handler in handlers:
            # Assuming handler is a class here
            binder.multibind(interface=List[Handler], to=handler())
```

It'll have the benefit of interacting nicely with static type checking. The old way of doing things (https://github.com/alecthomas/injector/blob/master/injector_test.py#L616-L622) will continue to work for the time being but is likely to be removed sooner rather than later.

If you're still having troubles with the current API please provide a piece of code that allows reproducing the problem.

**Comment by jstasiak** [comment]
0.17.0 has just been released, see updated [multibind documentation](https://injector.readthedocs.io/en/latest/api.html#injector.Binder.multibind) and the [relevant test code](https://github.com/alecthomas/injector/blob/c314e2197bafce4c98d2ba5b8bd2cc2a42e245ef/injector_test.py#L540). I'll close this issues, feel free to reopen if you encounter issues – code to reproduce with full stack trace will be appreciated.
