### ISSUE TITLE
Using Key with mypy support?

### ISSUE THREAD

**Issue by davidparsson** [alecthomas/injector#115]
Is it possible to use `Key` and not break `mypy` checks?

I have a class that's implementing a waiting strategy, which takes a sleep time (`float`) as an argument. I'd like to be able to configure this via Injector, and it seems a `Key` for this would be ideal. The problem is that this breaks my `mypy` check, since a `Key` is not a `float`.

```
SleepTime = Key('SleepTime')


class WaitStrategy:

    @inject
    def __init__(self, sleep_time: SleepTime = 1.0) -> None:
        self._sleep_time = sleep_time
```

The `mypy` log says:
```
error: Invalid type "wait_strategy.SleepTime"
```

My current work-around is to use a `Module` with a `@provider`.

**Comment by jstasiak** [comment]
[NewType](https://docs.python.org/3/library/typing.html#newtype) should work for you (Injector support has been [added a while back](https://github.com/alecthomas/injector/commit/5ae684c28ebbfd29a6a84f3ae8fdbb1317fc7bc4)).

I think `Key` will be removed at some point in the future as it creates issues like this.

**Comment by davidparsson** [comment]
Great news, it does! Thanks for a superb library, and for an impressively fast response! ❤️

**Comment by jstasiak** [comment]
You're welcome :)
