### ISSUE TITLE
When using NewType in typing, the error message is not thrown as in Key

### ISSUE THREAD

**Issue by wbaik** [alecthomas/injector#122]
While trying to understand your awesome library, I noticed `Key` is being deprecated. So from using NewType as suggested, the error message that should be generated is not thrown. 

```
from typing import NewType
from injector import inject, Injector, Key, Module, InstanceProvider, Binder

Name = NewType('name', str)
Description = NewType('description', str)

Name = Key('name')
Description = Key('description')

# class MyModule(Module):
#     def configure(self, binder):
#         binder.bind(Name, to='Sher')
#         binder.bind(Description, to='Desc')


class User:
    @inject
    def __init__(self, name: Name, description: Description) -> None:
        self.name = name
        self.description = description


class UserModule(Module):
    def configure(self, binder):
        binder.bind(User)


if __name__ == '__main__':
    injector = Injector([UserModule])
    print(injector)
    print('hi : {}'.format(injector.get(User)))
```
This would throw `Exception: Instantiation of <class 'injector.name'> prohibited - it is derived from BaseKey so most likely you should bind it to something.` if `Key` is used, but nothing in the case of `NewType`.

Is this intended? The original error message was very helpful, by the way.

**Comment by jstasiak** [comment]
I think this is an unfortunate consequence of the current implementation. See also https://github.com/alecthomas/injector/issues/116.
