### ISSUE TITLE
Multiple implementations of same interface

### ISSUE THREAD

**Issue by miguelgflores-fever** [alecthomas/injector#123]
Hello,

I've reading a lot, the code and issues and I don't see there is an easy solution to this without modifying the original classes and using "NewType".

This is a really common case in my application:

```python
class A(abc.ABC):
    @abc.abstractmethod
    def foo(self):
        pass

class B1(A):
    def foo(self):
        print("I am b1")

class B2(A):
    def foo(self):
        print("I am b2")

class C:
    @inject
    def __init__(self, b1: A):
        self.b = b1

class D:
    @inject
    def __init__(self, b2: A):
        self.b = b2
```

Here, if I bind `A` to either `B1` or `B2`, I will always get the same instance for A, but I want different implementation of the interface A depending on the client.

I can create new types for `A` and change on `C` class (and the same for `D`), but I want to respect the interfaces on the typehinting.

I seems like a really common case for me, what do you do on this cases?

Regards

**Comment by alecthomas** [comment]
You can bind multiple instances of the same value with a [Key](https://injector.readthedocs.io/en/latest/terminology.html#keys).

**Comment by alecthomas** [comment]
I'm curious though, how you're going to decide which instance to inject without changing the code for C or D?

**Comment by jstasiak** [comment]
Yeah, if you want different things in `C` and `D` I'd just request them explicitly. Or, if you really want to have different implementations of your interface active yet you don't want to refer to them by name you can have multiple `NewType`s that you can bind separately and then use in `C` and `D`.

It's type-safe for all intents and purposes, so I think this
> but I want to respect the interfaces on the typehinting

will be satisfied.

Although I have a feeling we don't fully understand what you're trying to achieve here so a more detailed example could shed some light on this.

**Comment by miguelgflores-fever** [comment]
First of all, thanks for your responses!

> You can bind multiple instances of the same class via a Key. 

This will force me to change my current code, hiding under some keys (only for the sake of DI) the true type of the dependencies.

> I'm curious though, how you're going to decide which instance to inject without changing the code for C or D?

That's the point of my question. Maybe Injector doesn't allow it and I must add a layer/wrapper to allow this, at least when I have an interface with multiple implementations, allow to say "For class `C`, the implementation of `A` to use is `B1` and for class `D`, the implementation of `A` to use is `B2`".

----

I'll add a (some sort) of real example of what I want to achieve, it may help:

```python

class FileSystem(abc.ABC):
    @abc.abstractmethod
    def write(self, content):
        pass

class LocalFileSystem(FileSystem):
    def write(self, content):
		fd = os.open(...)
		os.write(fd, content)
		os.close(fd)

class S3FileSystem(FileSystem):
    def write(self, content):
		boto.s3.write(..., content)

class LogWriter:
	def __init__(self, fs: FileSystem):
		self.fs = fs

    def write(self, content):
		self.fs.write(content)

# Nowdays, on my code (without any modification) I can achieve:

local_log_writer = LogWriter(LocalFileSystem())
s3_log_writer = LogWriter(S3FileSystem())

```

I can use one or the another without modifying my code, respecting the Dependency inversion principle. `LogWriter` doesn't need to know what kind of class is going to be injected so far as it respects `FileSystem` interface.

I hope you can understand what I try to achieve. In any case thank you very much for taking your time looking at this.

**Comment by jstasiak** [comment]
Ok, cool, I think I understand this now. Would it be accurate to say that in some places you want to inject `LogWriter that uses a LocalFileSystem writer` and sometimes `LogWriter that uses S3FileSystem writer` without having to create a two `NewType`-aliases aliasing `LogWriter` and binding them manually?

**Comment by miguelgflores-fever** [comment]
Yes, that's right

**Comment by jstasiak** [comment]
Ok, so: there's no builtin mechanism for saying "inject this implementation in class X but another implementation in class Y but still classes X and Y only request injection of an abstract interface", it needs to be done manually. You can provide a custom provider, use `AssistedBuilder` for this but it may not be too nice and will become repetitive.

I'm wondering if support for something like this could be added to Injector easily and if it was convenient enough for you – basically supporting generics and injecting based on type paremeters:

```python
from typing import Generic, TypeVar
from injector import inject

class FileSystem(abc.ABC):
    @abc.abstractmethod
    def write(self, content):
        pass

class LocalFileSystem(FileSystem):  # ...
class S3FileSystem(FileSystem):  # ...

T = TypeVar('T', bound=FileSystem)

class LogWriter(Generic[T]):
    @inject
    def __init__(self, fs: T):
        self.fs = fs

    def write(self, content):
        self.fs.write(content)



# Then somewhere else

class SomethingSomething:
    @inject
    def __init__(self, log_writer: LogWriter[LocalFileSystem]):
        # ...
```

**Comment by miguelgflores-fever** [comment]
Jakub Stasiak, thanks for taking the time replying.

I'm afraid that something like that don't work for us, for the level of abstraction we pursue on our application, where the services can't change their typehint or parameters for the sake of the library used for Injection.

I guess we can close this issue, we will work on some workaround to achieve this on our project (probably we must think on some manual mapping for the cases I've exposed, where we can manually specify what instance inject).

Still I hope this discussion is useful for somebody seeking the same information in the future.

And again, thank you!

**Comment by domgraziano** [comment]
@miguelgflores-fever I am running in exactly your same issue. Have you found an acceptable and simple way of achieving this ? And are you able to share it here? 
The only solution I figured out so far is to have an interface that define the contract and then sub interfaces that defines the types so then I can bind a subinterface to a specific implementation that implement the contract of the main interface via extension of the subinterface. It works but I don’t particularly like it as it’s high maintaining cost (I need to change the binder AND the injection if I want to change the implementation injected) and it’s open to misuses (one can still modify the sub interface, which is only there to work around the issue you described here, and that can lead to a Liskov violation)
I’d be interested in understand in hearing your experience with that.
If you’ll find the time to answer 
Thanks in advance :)

**Comment by miguelgf** [comment]
Hello @domgraziano 

Sadly we couldn't achieve this with this Injector (or any available) and we decided to create our own, we released it as open source, and we are using it on several projects.

Dependency Injection Container: https://github.com/Feverup/pypendency
Flask Extension for it: https://github.com/miguelgf/flask-pypendency

On our case, we were seeking to do exactly what I asked here, and we have the definitions of binding on one side (either a .py or a .yaml file) and the classes on another. Then we ask to the container to give us the instance, and he does. It works on a lazy way and avoids cyclic references on the definitions.

Hope it helps!

**Comment by domgraziano** [comment]
@miguelgf thanks for sharing this! I struggled a lot in finding a valid alternative that does that in the pythonland and what you just described is exactly what I’m looking for as it’s closer to the standard definition of a IOC container used in conjunction with the Liskov substitution principle and more in general “programming to an interface”. Something that I use daily in frameworks like symfony (on the php side of things). Yes I want to change only definition in my container, nothing else, only the bindings (or wirings).
I’ll have a play with yours and give you a feedback if you like :) 

Thanks again

**Comment by miguelgf** [comment]
@domgraziano sure! If you need any help you can contact me directly on miguelgzflores@gmail.com as the documentation is not very detailed, but we are using it on several projects, we can use your use case to improve it in case you have any trouble. 

Regards

**Comment by bschnitz** [comment]
When I recently stumbled over this problem, I found, that the idea described in [one of the comments above](https://github.com/python-injector/injector/issues/123#issuecomment-521941276) can already be implemented quite easily by hacking the `ClassAssistedBuilder` class a bit and I just wanted to share it for anyone stubling accross this again:
```python
from abc import abstractmethod
from inspect import getfullargspec
from typing import Any, get_origin
from injector import ClassAssistedBuilder, Injector, inject


class SomeInterface:
    @abstractmethod
    def hello(self):
        pass

class Impl1(SomeInterface):
    def hello(self):
        print("holla")

class Impl2(SomeInterface):
    def hello(self):
        print("hallo")

class ImplUser[S, T]:
    @inject
    def __init__(self, injector: Injector, implS: S, implT: T):
        implS.hello()
        implT.hello()

class InstanceMapper[T](ClassAssistedBuilder):
    @inject
    def __init__(self, injector: Injector, genericType: T):
        genericOrigin = get_origin(genericType)
        implementations = get_args(genericType)
        paramToImpl = dict(zip(genericOrigin.__type_params__, implementations))
        fullspec = getfullargspec(genericOrigin.__init__).annotations
        self.argToImpl = {k: paramToImpl[v] for k, v in fullspec.items() if v in paramToImpl}
        super().__init__(injector, genericOrigin)

    def build(self, **kwargs: Any) -> T:
        build_args = {k: injector.get(v) for k, v in self.argToImpl.items()}
        return super().build(**{**build_args, **kwargs})
        
injector = Injector()
implUser = injector.get(InstanceMapper[ImplUser[Impl1, Impl2]])
implUser.build()
```
