### ISSUE TITLE
[Regression] injector.BoundKey

### ISSUE THREAD

**Issue by Stael** [alecthomas/injector#125]
Hi, 
I have found a small regression in this snippet, which is provided as example on how to use the BoundKey here: https://injector.readthedocs.io/en/latest/api.html#injector.BoundKey

```
from injector import Injector, BoundKey, InstanceProvider

class A:
    def __init__(self, a, b):
        self.a = a
        self.b = b

InjectedA = BoundKey(A, a=InstanceProvider(1), b=InstanceProvider(2))
injector = Injector()
a = injector.get(InjectedA)
a.a, a.b
```

It works in 0.15, 0.16 but fails in 0.17 with the following error:
`UnknownProvider: couldn't determine provider for InstanceProvider(1) to None`

Hope this helps :)
Have a good day !

**Comment by jstasiak** [comment]
The fix for this has just been released as part of the version 0.18.1.
