### ISSUE TITLE
0.18 release?

### ISSUE THREAD

**Issue by asyncee** [alecthomas/injector#127]
Hello, it seems that documentation already points to 0.18 (https://injector.readthedocs.io/en/latest/api.html#injector.NoInject), but in pypi it is still 0.17.

Am i missing something or there are no 0.18 published yet?

**Comment by jstasiak** [comment]
Yeah it's not published yet. I'm not sure if releasing it before https://github.com/python/mypy/issues/7729 gets fixed is the right thing to do as the issue is quite serious (no type checking when `Inject` and `NoInject` are used).

**Comment by asyncee** [comment]
Thank you for quick response!

**Comment by jstasiak** [comment]
@asyncee this may interest you: https://github.com/python/mypy/issues/7729 is resolved now, so with an extra note added regarding Mypy compatibility (https://github.com/alecthomas/injector/commit/ddc73e1aa9282f3d1bed44cc0396dc9b5e0ab010) I just shipped 0.18.0 to PyPI.

**Comment by asyncee** [comment]
Thats great, thank you, sir!
