### ISSUE TITLE
@provider decorator does not support forward references

### ISSUE THREAD

**Issue by eugenhu** [alecthomas/injector#130]
Running the following example (I am using Python 3.5.7),
```python
from injector import Injector, Module, inject, provider


class MyModule(Module):
    @provider
    def provide(self) -> 'X':
        return X('hello')


@inject
def fun(s: 'X') -> 'X':
    return s


class X:
    def __init__(self, message: str) -> None:
        self.message = message


injector = Injector(modules=[MyModule], auto_bind=False)
print(injector.call_with_injection(fun).message)
```

I get an `UnsatisfiedRequirement` error. Rearranging to avoid forward references fixes this.

I think this is because `_mark_provider_function()`

https://github.com/alecthomas/injector/blob/f529eec73d7e52d253735247dc770b680dea3898/injector/__init__.py#L1165-L1176

uses `inspector.getfullargspec()` to determine the return type, which I don't think resolves string literal annotations.

We could replace line 1167 with
```python
annotations = get_type_hints(function)
```
but running the example again we get,
```
NameError: name 'X' is not defined
```
which I think is because the forward reference is trying to be resolved by the `@provider` decorator before `X` is defined.

I don't know if there is an easy fix to this. One idea is to change the implementation of `_mark_provider_function()` to
```python
def _mark_provider_function(function: Callable, *, allow_multi: bool) -> None:
    if not allow_multi:
        function.__is_provider__ = 'provider'
    else:
        function.__is_provider__ = 'multiprovider'
```
and then move the original `Binding` creating logic into `Module.__call__()`.

A downside to this is that the "Function needs to be decorated with a multiprovider" error won't be raised until when the module is being configured.

Alternatively, maybe if `get_type_hints(function)` fails, we could set `function.__binding__` to `'deferred'` (and then try creating the `Binding` object when the module is configured) and have some way of flagging the provider as a multiprovider.

**Comment by jstasiak** [comment]
Thanks for the report, check out version 0.18.2 (just released) – it should work.
