### ISSUE TITLE
Question about providers

### ISSUE THREAD

**Issue by JGiard** [alecthomas/injector#132]
Hi,
I'm currently planning a migration to `injector` from a custom package that I wrote (https://github.com/JGiard/Pynject),
and I have a question about how to best address a specific case :
I used to be able get objects injected into my providers like
```python
class FooProvider(Provider):
    @inject
    def __init__(bar: Bar):
        self.bar = bar

    def get(self) -> Foo:
        return Foo(do_stuff_with_bar(self.bar))
```

As I understand that's not possible with this injector, and I need to use something like the `@provider` annotation on modules

```python
class FooModule(Module):
    @provider
    def get_foo(self, bar: Bar) -> Foo:
        return Foo(do_stuff_with_bar(self.bar))
```

However I have a bunch of those, and I'd rather not put them all in one module. And having to pass them all to the injector constructor seems prone to forgetting one.
I haven't found documentation about nesting modules, but it looks like you can just `install` submodules like in guice
```python
class MyModule(Module):
    def configure(self, binder: Binder):
        binder.bind(Bar, to=Bar())
        binder.install(FooModule) # will bind Foo to get_foo()
```
Is this something correct to write ?
Thank you if you take time to read this and give me some feedback.

**Comment by jstasiak** [comment]
Hey, sure, you could do that and installing modules by other modules is supported. There are few other options here, maybe you'll like them better.

If you have a look at the [bind() documentation](https://injector.readthedocs.io/en/latest/api.html#injector.Binder.bind) you'll see that for any given type `T` you can, apart from not binding to anything explicitly or binding to an instance of `T`, bind to:
1. An instance of `Provider[T]`
2. A callable returning `T`

In the first case your code would look like:

```python

class FooProvider(Provider[Foo]):
    def get(self, injector: Injector) -> Foo:
        return Foo(do_stuff_with_bar(injector.get(Bar)))

class BazProvider(Provider[Baz]):
    def get(self, injector: Injector) -> Baz:
        return Baz(do_other_stuff_with_bar(injector.get(Bar)))

class MyModule(Module):
    def configure(self, binder: Binder) -> None:
        binder.bind(Foo, to=FooProvider())
        binder.bind(Baz, to=BazProvider())
```

But that's quite repetitive and for little to no gain. I'd recommend binding to a callable directly in this case:

```python

# return annotation is not necessary, but good to have it anyway
def provide_foo(bar: Bar) -> Foo:
        return Foo(do_stuff_with_bar(bar))

def provide_baz(bar: Bar) -> Baz:
        return Baz(do_other_stuff_with_bar(bar))

class MyModule(Module):
    def configure(self, binder: Binder) -> None:
        binder.bind(Foo, to=provide_foo)
        binder.bind(Baz, to=provide_baz)
```

I added some [documentation to clarify that this is possible](https://github.com/alecthomas/injector/commit/e6d55adf6f3bf11443ea95e935eac80966ca4bbf).

It's possible to have `do_stuff_with_bar` return a distinct type, let's say `BarProcessed` and this simplifies things even more:

```python
class MyModule(Module):
    def configure(self, binder: Binder) -> None:
        binder.bind(BarProcessed, to=do_stuff_with_bar)

# Make Foo and Baz expect BarProcessed in their constructors and no configuration will be needed here.

```

but that's to you to evaluate, as only you know the rest of the code.

**Comment by JGiard** [comment]
I think I will take the second option with function providers, thank you for your help !
