### ISSUE TITLE
I'm not able to test my injectable class

### ISSUE THREAD

**Issue by mayermatheus** [alecthomas/injector#146]
Versions:
- injector==0.18.3
- Flask-Injector==0.12.3
- python == 3.6.9

Problem:
I am looking to test a service which has the inject annotation in its constructor to be injectable. However, I am not able to test it. According to the documentation I need to do this:
import unittest
from injector import Module, with_injector, inject

```python
class UsernameModule(Module):
    def configure(self, binder):
        binder.bind(str, 'Maria')

class TestSomethingClass(unittest.TestCase):
    @with_injector(UsernameModule())
    def setUp(self):
        pass

    @inject
    def test_username(self, username: str):
        self.assertEqual(username, 'Maria')
```

But copying and pasting this code without touching anything, gives the following problem:
![image](https://user-images.githubusercontent.com/13408982/85282516-41aef080-b462-11ea-96d2-a1046a716fbb.png)

Can anybody help me?

**Comment by jstasiak** [comment]
Ugh, sorry, I forgot to remove this part of the documentation. `with_injector` is gone. You need to create an instance of Injector on your own and use it, the simplest case

```python
def test_username(self):
    injector = Injector(UsernameModule())
    assert injector.get('str') == 'Maria'
```

**Comment by mayermatheus** [comment]
@jstasiak It would look like this: from injector import Module, Injector, inject?

**Comment by jstasiak** [comment]
Yup

**Comment by mayermatheus** [comment]
@jstasiak Could you update the documentation, please? I'm doing a task to insert the unit tests in the project kkkkk

**Comment by outofthecave** [comment]
Why is this issue closed?  The docs in master are still incorrect: https://github.com/alecthomas/injector/blob/master/docs/testing.rst
