### ISSUE TITLE
Binding NewType classes without mypy warnings?

### ISSUE THREAD

**Issue by davidparsson** [alecthomas/injector#148]
Is it possible to somehow bind a `NewType` to a particular class without casting?

Consider this:
```python
MyType = NewType('MyType', SomeClass)
injector.binder.bind(MyType, to=SomeClass)  # Error
```

That gives the following error:
```
error: Argument "to" to "bind" of "Binder" has incompatible type "Type[SomeClass]"; expected "Union[MyType, Callable[..., MyType], Provider[MyType]]"
```

This might be a mypy issue, but I haven't found a way around it without casting. Do you know of any?

**Comment by davidparsson** [comment]
This is my current workaround:
```python
MyType = NewType('MyType', SomeClass)
injector.binder.bind(MyType, to=cast(Type[MyType], SomeClass))
```

**Comment by jstasiak** [comment]
I think that requires a cast on purpose. Does `bind(MyType, to=MyType)` or just `bind(MyType)` work for you maybe? I'd expect it to work but maybe I haven't tested this particular case.

**Comment by davidparsson** [comment]
That might work, but in practice I want to bind subclasses of `SomeClass` so that does not really solve things for me.

**Comment by davidparsson** [comment]
Thanks for the idea, though!

**Comment by jstasiak** [comment]
Oh yes, then casting is necessary I'm afraid. :)

**Comment by davidparsson** [comment]
Then I guess this too is a mypy issue more than anything else.

**Comment by jstasiak** [comment]
I think this is not even a mypy issue – this is working as intended, the type system is not expressive enough to handle this particular relationship with the current annotations so it is what it is.
