### ISSUE TITLE
Feature request: boot method for modules

### ISSUE THREAD

**Issue by vryazanov** [alecthomas/injector#151]
Hi there,
It would be great to have `boot` method inside `Module` that will be called after all modules are configured, wdyt?
Sometime I want, for example, connect signals to receivers or something like that. and looks like this method will be a nice place for that.

**Comment by jstasiak** [comment]
You can do all that once you have an `Injector` instance, because its constructor configures all modules so I don't see much benefit of introducing this API. Already possible now:

```
modules = ...
injector = Injector(modules)
for module in modules:
    if hasattr(module, 'boot'):
        module.boot(...)
```
