### ISSUE TITLE
from injector import provides error

### ISSUE THREAD

**Issue by dhulke** [alecthomas/injector#156]
I'm getting the following error when trying to import the provides module:

```
Exception occurred:
  File "/mnt/c/Users/green/git/foxtrot/app/spark/services/di/end_customer_portal_modules.py", line 1, in <module>
    from injector import Module, inject, provides, singleton, Key
ImportError: cannot import name 'provides' from 'injector' (/mnt/c/Users/green/git/foxtrot/foxtrotwsl/lib/python3.8/site-packages/injector/__init__.py)
The full traceback has been saved in /tmp/sphinx-err-j00u6gu_.log, if you want to report the issue to the developers.
```

I'm using python 3.8.2 and injector 0.18.4

**Comment by jstasiak** [comment]
[`provides` has been removed long time ago](https://github.com/alecthomas/injector/commit/2f665491672d7dd0b40d55937970cb9bd6bd4ca7), is it still present somewhere in the documentation?

**Comment by dhulke** [comment]
Good to know. So it was replaced by provider? It wasn't in any documentation, just some legacy code that failed to installed because I lost the requirements.txt and tried recreating it from scratch. I just tried an older version and it worked.

Thank you.

**Comment by jstasiak** [comment]
Yes, `provider` is the replacement for it.
