### ISSUE TITLE
Help to add injector in django rest framework

### ISSUE THREAD

**Issue by Vaunorage** [alecthomas/injector#157]
Hi !

I wanted to add the injector to my django app. However, I do not know how to ?

Could someone help me with a guide please ?
 
Thanks

**Comment by jstasiak** [comment]
You can try https://github.com/blubber/django_injector (I can only endorse version 0.0.2, as https://github.com/blubber/django_injector/pull/3 present in newer version goes a bit against the Injector philosophy IMO), I don't know if it works with Django REST Framework though. Shouldn't be too difficult to make if work if it doesn't.

**Comment by jstasiak** [comment]
Seems like https://github.com/blubber/django_injector supports Django REST Framework so I'll close this issue.
