### ISSUE TITLE
[Question] unbind multibindings' instances

### ISSUE THREAD

**Issue by mozesa** [alecthomas/injector#159]
Hello **jstasiak**,

I would like to ask for some help.

I want to leverage `injector`'s multibindigs ability in order to register running instances of Station class.

How would it be possible to unbind/remove/delete certain multibindings' instances?

```python
async def worker(self, station_no: int, routing_lines: list) -> None:
    station = Station(station_no, routing_lines)
    try:
        self.binder.multibind(list[Station], to=[station])
        await station.run()
    finally:
        # del station's instance
        pass
```

I really appreciate your help.

Thanks in advance.

**Comment by jstasiak** [comment]
Hey, I'm afraid this is out of scope of this project. In general it's expected that the bindings are more or less static after the application startup (as in: no new bindings are added after Injector instance is created /this can be done though, as your case demonstrates/ and bindings aren't removed /there's no API for it/).

I suggest you create a class (that's a singleton within Injector or any other scope that makes sense in your case) that holds the list of instances of `Station` at the time and has the `add/remove/get` API that you need.

**Comment by mozesa** [comment]
What about `Scopes`? How are those related to it?

**Comment by jstasiak** [comment]
You'll want to share the instance of your class between places that'll use it, see https://injector.readthedocs.io/en/latest/terminology.html#scope

**Comment by mozesa** [comment]
Thanks for your help!
