### ISSUE TITLE
Many mypy issues in python 3.7

### ISSUE THREAD

**Issue by davebirch** [alecthomas/injector#176]
Hey, me again. Decided to have a quick poke at python 3.7 support and it was all going well until I ran mypy!

Seeing a whole host of issues that look very reproducable. 

All uses of @inject and @noninjectable are triggering a warning - these can be worked around by moving the decorators to the class:
`error: Untyped decorator makes function "__init__" untyped  [misc]`

It also appears that the build() method of AssistedBuilder is returning Any, passing on the object it builds from a typed method gets me a warning:
Assuming type `AssistedBuilder[BuiltType]`
`error: Returning Any from function declared to return "BuiltType"  [no-any-return]`

Finally, every location in my code where I extend Module, I get a:
`error: Class cannot subclass 'Module' (has type 'Any')  [misc]`

I don't see any of these same issues on either 3.6 or 3.8 - they seem exclusive to 3.7

I could probably just cast things, ignore warnings and work around it all, just wondered if it was indicative of some kind of typing issue with injector in 3.7?

**Comment by jstasiak** [comment]
Can you provide the exact version of Python 3.7 you're using together with Injector and mypy versions, a code sample to reproduce the issue and mypy output?

**Comment by davebirch** [comment]
Looks like this was an issue in python 3.7.6, but was fixed by and upgrade 3.7.9.

I also believe the problem was occurring in some of our internal tooling, rather than injector, closing this issue :)

**Comment by jstasiak** [comment]
Thank you for the update :).
