### ISSUE TITLE
Multibinder requires instances.

### ISSUE THREAD

**Issue by richburdon** [alecthomas/injector#45]
I often use multi-binding where I want to use DI to create instances of the sequence -- hence I can't bind instances directly to the sequence key. My workaround is the utility class below, but it feels like this should be built into the framework (esp. since ListOfProviders is markes @private)

``` python
binder.multibind(Test.SEQ_KEY, ClassProviderList([MyClass])) # Not an instance.

class ClassProviderList(ListOfProviders):
    def __init__(self, classes):
        super(ClassProviderList, self).__init__()
        for cls in classes:
            self.append(ClassProvider(cls))
```

**Comment by alecthomas** [comment]
Sure, that makes sense to me. Send a PR with tests and I'll be happy to merge it.

**Comment by Letsch22** [comment]
In my own projects I've been finding myself reaching for this functionality, I opened #197 to add it.

**Comment by KrzysztofMadejski** [comment]
I just ran into the same need. It's quite of a gap that `multibind` can't work with `ClassProvider` as normal `bind` would.
