### ISSUE TITLE
Too hard to find unbound keys.

### ISSUE THREAD

**Issue by richburdon** [alecthomas/injector#48]
When something isn't bound it's very difficult to find what is missing. The error looks like this (after 30 lines of injector.py code):

TypeError: __init__() takes exactly 2 arguments (1 given)

There is no mention to the Key or class that is missing.

It would also be really useful to be able to list all bound (and non-bound) keys.

**Comment by alecthomas** [comment]
Is this correct? I get the following when injecting an instance:

```python
injector.CallError: Call to A.__init__(a=1) failed: __init__() takes exactly 3 arguments (2 given) (injection stack: [])
```

Are you using the most recent version? If so, can you provide some minimal code to replicate?
