### ISSUE TITLE
Singleton scope leaks instances from child injectors

### ISSUE THREAD

**Issue by canni** [alecthomas/injector#52]
# Show me the code

This test fails, and IMO it shouldn't according to `SingletonScope` docs, instances are stored _per injector_ so I'd expect this test to pass with no trouble

```
class TestChildScope(unittest.TestCase):
    def test_child_scope(self):
        TestKey = Key('test')
        TestKey2 = Key('test2')

        def parent_module(binder):
            binder.bind(TestKey, to=object, scope=singleton)

        def first_child_module(binder):
            binder.bind(TestKey2, to=object, scope=singleton)

        def second_child_module(binder):
            binder.bind(TestKey2, to='marker', scope=singleton)

        injector = Injector(modules=[parent_module])
        first_child_injector = injector.create_child_injector(modules=[first_child_module])
        second_child_injector = injector.create_child_injector(modules=[second_child_module])

        self.assertIsNot(first_child_injector.get(TestKey2), second_child_injector.get(TestKey2))
```

**Comment by canni** [comment]
Another test that IMO should pass, but fails (With work-around that fixes 1st test):

    class TestChildScope(unittest.TestCase):
        def test_child_scope(self):
            TestKey = Key('test')
            TestKey2 = Key('test2')

            def parent_module(binder):
                binder.bind(TestKey, to=object, scope=singleton)

            def first_child_module(binder):
                binder.bind_scope(SingletonScope)
                binder.bind(TestKey2, to=object, scope=singleton)

            def second_child_module(binder):
                binder.bind_scope(SingletonScope)
                binder.bind(TestKey2, to='marker', scope=singleton)

            injector = Injector(modules=[parent_module])
            first_child_injector = injector.create_child_injector(modules=[first_child_module])
            second_child_injector = injector.create_child_injector(modules=[second_child_module])

            self.assertIsNot(first_child_injector.get(TestKey2), second_child_injector.get(TestKey2))
            self.assertIs(first_child_injector.get(TestKey), second_child_injector.get(TestKey))

**Comment by jstasiak** [comment]
This is fixed by https://github.com/alecthomas/injector/commit/de979a013be4cc3e9c6ae2ca667ce92c64213ca2 (soon to be released)
