### ISSUE TITLE
BoundProvider.__repr__() causes TypeError 

### ISSUE THREAD

**Issue by jonnyt886** [alecthomas/injector#53]
BounderProvider.__repr__() looks like this:

```
def __repr__(self):
    return 'BoundProvider(%r, %r)' % (
        type(self).__name__, self._injector, self._interface)         
```

When called this causes 

> TypeError not all arguments were converted to String

This appears to be because two format arguments are specified (the two %r's) but three are given in the tuple. The way to fix this is to replace the hard-coded 'BoundProvider' with '%r' so the number of arguments match:
```
def __repr__(self):
    return '%r(%r, %r)' % (
        type(self).__name__, self._injector, self._interface)         
```

**Comment by jstasiak** [comment]
This is fixed in https://github.com/alecthomas/injector/commit/f7f9f02e94b871a9bc5b037ed867865ac378eb64 but not released yet.

**Comment by alecthomas** [comment]
@jstasiak sorry, I thought I'd given you admin rights on PyPi. What's your PyPi username?

**Comment by alecthomas** [comment]
Disregard, I found you. Feel free to push out releases whenever you feel it necessary.

**Comment by jstasiak** [comment]
I'll close this as the fix has been release. @jonnyt886 The 0.10.1 and 0.11.1 versions contain the fix for this, the 0.11.1 is substantially backwards incompatible though (just a heads-up).

**Comment by alecthomas** [comment]
BTW @jstasiak; if you install pypandoc + pandoc before you sdist, then setup.py will convert the README.md file to .rst so that the docs on pypi get formatted correctly.

**Comment by jstasiak** [comment]
Yeah, I managed to forget about it twice this week already, I have it installed now though :)
