### ISSUE TITLE
Example from "Testing with Injector" doesn't work

### ISSUE THREAD

**Issue by tavianator** [alecthomas/injector#64]
I tried the example from [Testing with Injector](https://injector.readthedocs.io/en/latest/testing.html)

```python
import unittest
from injector import Module, with_injector, inject

class UsernameModule(Module):
    def configure(self, binder):
        binder.bind(str, 'Maria')

class TestSomethingClass(unittest.TestCase):
    @with_injector(UsernameModule())
    def setUp(self):
        pass

    @inject(username=str)
    def test_username(self, username):
        self.assertEqual(username, 'Maria')
```

But it didn't work:

```
======================================================================
ERROR: test_username (tests.TestSomethingClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tavianator/.virtualenvs/py3/lib/python3.6/site-packages/injector.py", line 1153, in inject
    return f(self_, *args, **kwargs)
TypeError: test_username() missing 1 required positional argument: 'username'
```

This is with injector 0.12.

**Comment by alecthomas** [comment]
The documentation is incorrect. It should be used on each method like so:

```
import unittest
from injector import Module, with_injector, inject

class UsernameModule(Module):
    def configure(self, binder):
        binder.bind(str, 'Maria')

class TestSomethingClass(unittest.TestCase):
    def setUp(self):
        pass

    @with_injector(UsernameModule())
    @inject(username=str)
    def test_username(self, username):
        self.assertEqual(username, 'Maria')
        print('foo')

if __name__ == '__main__':
    unittest.main()
```

Alternatively you could apply this to `setUp()`, and assign the injected attributes to fields.

I'll update the documentation.

**Comment by alecthomas** [comment]
Though...that is quite annoying. It would be more useful if it did what the documentation suggests.

Fixed in 57d73f6055bec0535b886dcf79bc2e064d463497.

**Comment by alecthomas** [comment]
0.12.1 released with this change.

**Comment by tavianator** [comment]
Awesome, thank you!

**Comment by passjwhub** [comment]
> The documentation is incorrect. It should be used on each method like so:
> 
> ```python
> import unittest
> from injector import Module, with_injector, inject
> 
> class UsernameModule(Module):
>     def configure(self, binder):
>         binder.bind(str, 'Maria')
> 
> class TestSomethingClass(unittest.TestCase):
>     def setUp(self):
>         pass
> 
>     @with_injector(UsernameModule())
>     @inject(username=str)
>     def test_username(self, username):
>         self.assertEqual(username, 'Maria')
>         print('foo')
> 
> if __name__ == '__main__':
>     unittest.main()
> ```
> 
> Alternatively you could apply this to `setUp()`, and assign the injected attributes to fields.
> 
> I'll update the documentation.

#===================================
Hi, I am trying to do this at injector 0.18.3,  there are error like this:

>>> import injector
>>> injector.__version__
'0.18.3'
>>> from injector import with_injector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'with_injector'
>>>

do you  remove with_injector from injector.__init__ ?  I can not search for that also.

**Comment by outofthecave** [comment]
@passjwhub The decorator `@with_injector` was removed in version 0.16.0, but the documentation was not updated.  See https://github.com/alecthomas/injector/issues/146 and https://github.com/alecthomas/injector/issues/150
