### ISSUE TITLE
Keyword arguments to @inject in future releases

### ISSUE THREAD

**Issue by Dominik1123** [alecthomas/injector#65]
I just read the [changelog for `0.11.0`](https://injector.readthedocs.io/en/latest/changelog.html#id2) and saw that keyword arguments to the `@inject` decorator will be removed in favor of type annotations in a future release. Does that mean that you plan to drop Python 2.x support completely? If not what is the reason for dropping Python2/3 compatibility?

**Comment by alecthomas** [comment]
I personally don't think it's unreasonable, but @jstasiak wrote that so I'll leave it to him to comment.

**Comment by jstasiak** [comment]
Yes, I'd like to drop Python 2 support eventually and the change you mention helps here.

The reasons to do so are (in random order and from my point of view):
* reduced maintenance burden
* being able to annotate the code with type hints directly
* better experience when injector is used in code tested by static type checker(s)
* helping giving projects still using Python 2 a little incentive to consider Python 3 migration

**Comment by Dominik1123** [comment]
Thanks for clarifying! No problem from my side, I just got to fix the version number in my project's dependencies then until I migrate it to Python 3.
