### ISSUE TITLE
Missing getfullargspec in python 2.7

### ISSUE THREAD

**Issue by hellerbarde** [alecthomas/injector#66]
In Python 2.7, using `@provider` throws an error, because `getfullargspec` is `None`

I tried to add a shim, but since it uses the annotations attribute to determine the return type, this won't work in python 2.7

I am unsure how to fix this.

**Comment by jstasiak** [comment]
Hey, sorry about the confusion. I added a piece of documentation in 408b7fcaaa97974e19086bd90c05ecdb4da3da93 that should clarify things - this won't work on Python 2.

**Comment by hellerbarde** [comment]
Thanks for the quick response. 

Maybe @provides shouldnt be marked deprecated quite yet then? 

Or whats the idiomatic way of doing this in python 2?

**Comment by jstasiak** [comment]
The idiomatic Python 2 way of doing that is to keep using ``@provides``.

I'd pin the dependency version (if you're not already doing it) because the next Injector release will be Python 3-only and will not contain the Python 2 baggage, hence the deprecation mark.

**Comment by hellerbarde** [comment]
👍 I see. Thanks for the quick response!
