### ISSUE TITLE
injector in connexion broken with version 0.13.0 ?

### ISSUE THREAD

**Issue by tjhgit** [alecthomas/injector#67]
I get the following error message with the latest 0.13.0 version:
File "/usr/local/lib/python3.6/site-packages/injector.py", line 1014, in inject
    raise AssertionError('Wrong use of the inject decorator, please consult the documentation')

when trying the code of part1 here:
https://medium.com/@ssola/building-microservices-with-python-part-i-5240a8dcc2fb

Works like a charm with version 0.12.1 !

**Comment by jstasiak** [comment]
Hi,

Judging by the content of the article mentioned this is not related to connexion but to usage of ``@inject`` with keyword arguments. Using ``@inject`` with keyword arguments has been removed in injector 0.13 (https://github.com/alecthomas/injector/commit/89afd15dbfaedb81656b9bdddde2984d7b569d65) and only parameter annotations are used now to declare dependency types.

Granted, the error message could be better so I'll change it.

**Comment by tjhgit** [comment]
Hi,

thanks I was not aware of this change. Changed the source code to 
```
@inject
def search(data_provider: ItemsProvider):
```
and this works now nicely with 0.13 👍 

Maybe you can optimize the error message, though.
