### ISSUE TITLE
How to access injector instances in dependency instance

### ISSUE THREAD

**Issue by michealsong** [alecthomas/injector#71]
Hi,

I have a use case.

There are two dependencies:
``` python
class A(object):
    @inject()
    def init(self):
        pass
    
    def somefunc(self):
          b = B()
```

``` ptyhon
class B(object):
    @inject(c=C):
    def init(self, c):
         self.c = c
```

I get an injector instance
`injector = Injector()`

Then, I get an instance of `A`
`a = injector.get(A)`

I want to create a new instance of `B`, when I call `somefunc` of `A` every time.
How can I use injection to get an instance B in this situation?

**Comment by juharris** [comment]
Inject a `ProviderOf[B]` into `A` and use that.

**Comment by michealsong** [comment]
Is `ProviderOf[B]` a factory class which has a method to return an instance of B?

Or is it a subclass of build-in class in `injector` module?

**Comment by jstasiak** [comment]
It's a class with a single public method (``get()``)[1] which interacts with Injector internally to get an instance of ``SomeClass`` every time it's called[2].

[1] http://injector.readthedocs.io/en/latest/api.html#injector.ProviderOf
[2] If ``SomeClass``'s scope is set to ``singleton`` ``ProviderOf[SomeClass].get()`` will keep returning the same value though, for example.
