### ISSUE TITLE
Can't create PyQt objects annotated with @inject

### ISSUE THREAD

**Issue by davidparsson** [alecthomas/injector#75]
If a class that inherits from a PyQt class, for example `QObject`, is annotated with `@inject`, it can't be created without using Injector. The [`getattr()` in `@inject`](https://github.com/alecthomas/injector/blob/4faa3f77c25342eddb5b092442c2f29ba9656541/injector.py#L1072) raises a `RuntimeError`. Here's an example:

```
from PyQt5.QtCore import QObject
from injector import inject, Injector

class C(QObject):
    @inject
    def __init__(self):
        super().__init__()

injector = Injector()
c = injector.create_object(C)  # This works

c = C()  # This raises a RuntimeError
```

This is the traceback:
```
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    c = C()
  File ".../lib/python3.6/site-packages/injector.py", line 1072, in inject
    injector = getattr(self_, '__injector__', None)
RuntimeError: super-class __init__() of type C was never called
```

I've used PyQt 5.8 and Injector 0.13.2.

**Comment by davidparsson** [comment]
The first idea that comes to mind is to wrap the `getattr()` in a try-except block and treat the exception as no injector was found:
```
try:
    injector = getattr(self_, '__injector__', None)
except Exception:
    injector = None
```

Do you think this is an acceptable solution? If so, I could open a PR.

**Comment by jstasiak** [comment]
Hey! It's an acceptable solution with one change - only ``RuntimeError`` needs to be caught. It'd be cool to have a PR, I'd ask you to provide a unit test though.

**Comment by davidparsson** [comment]
@jstasiak, done! Could I expect this to be released any time soon?

**Comment by davidparsson** [comment]
I'd really appreciate an estimate on when I could expect this to be released. I have some code that depends on this, and if it will take more than a day or two I'll have to work around it.

Thanks for your efforts!

**Comment by jstasiak** [comment]
Thanks for the patch, I'll release it in few minutes.

**Comment by davidparsson** [comment]
Much appreciated! Thanks again!
