### ISSUE TITLE
Using default argument values in 0.13?

### ISSUE THREAD

**Issue by davidparsson** [alecthomas/injector#78]
In previous versions (0.12.x) of Injector, we've used the bindings in `@inject` to allow using the default values when injecting objects automatically, and using the `AssistedBuilder` when overriding is wanted:

```
class MyClass:
    @inject(other=OtherClass)
    def __init__(self, other: OtherClass, title: str = 'Default title'):
```

In 0.13.x the ability to provide bindings like this has been removed. Is there any recommended way to make Injector use the default values, that also works when creating the object without using Injector?

**Comment by jstasiak** [comment]
The ``noninjectable`` decorator[1] will tell Injector to not try to provide the value for a parameter and it'll let you do what you need:

```python
>>> import injector
>>> 
>>> class MyClass:
  2     @injector.inject
  3     @injector.noninjectable('title')
  4     def __init__(self, title: str = 'Default Title') -> None:
  5         self.title = title
>>> 
>>> injector_ = injector.Injector()
>>> injector_.get(MyClass).title
'Default Title'
>>> 
>>> builder = injector_.get(injector.AssistedBuilder[MyClass])
>>> builder.build(title='Doctor Who').title
'Doctor Who'
```

[1] https://injector.readthedocs.io/en/latest/api.html#injector.noninjectable

**Comment by davidparsson** [comment]
Oh, great, thanks! I guess I should have found that myself.

The fact that injector injects "value types" (such as `str`, `int`, `bool`) is a bit counterintuitive to me, especially when there's a default value. But the `noninjectable` decorator at least gives the option to handle the case.

**Comment by davidparsson** [comment]
That being said, my issues are resolved. Feel free to close this issue if you don't want to change the way default arguments are handled. Thanks for your help!
