### ISSUE TITLE
How to prioritize multibinds?

### ISSUE THREAD

**Issue by justanr** [alecthomas/injector#81]
I didn't see any mention of this in the docs and I haven't dug through the code thoroughly so feel free to point me at something I've potentially missed and tell me I've over thought this.

The use case here is allowing certain implementations to have a higher or lower priority based when dealing with non-deterministic registration.

Let's say I have some interface:

```python
class AuthenticationHandler(ABC):
    def authenticate(self, identifier: str, secret: str) -> Optional[User]:
        pass
```

And two implementations: `DefaultAuthHandler` and `LDAPAuthHandler`. This is easy enough to prioritize if I am the only one registering these into the application:

```python
# see injector #45
# these are purposefully decomposed for sake of example
binder.multibind(AuthenticationHandler, to=ClassProviderList([LDAPAuthHandler]))
binder.multibind(AuthenticationHandler, to=ClassProviderList([DefaultAuthHandler]))
```

However, if I provide a plugin hook for users to provide their own modules, I can no longer guarantee order. At most I can guarantee that either my implementations always come before or after their implementations, but they can't be interleaved.

A user may want to provide an implementation that uses `/etc/shadow` as an auth source but have it come in between my LDAP and Default implementations.

I'd like to know if there is either support for this in injector. Barring that, it would seem that a custom provider would be the most straightforward approach:

```python
class PrioritizedProvider(ClassProvider):
    def __init__(self, cls, priority: int=0):
        super().__init__(cls)
        self.priority = priority
```

However, this would also require being able to provide a custom provider *inside* multibind that can handle sorting these providers, something along the lines of:

```python
_default_key = lambda provider: getattr(provider, 'priority', 0)

class PrioritizedListOfProviders(ListOfProviders):
    def __init__(self, ordering=None):
        super().__init__()
        self.__sorted = False
        self.__ordering = ordering or _default_key

    def append(self, provider):
        super().append(provider)
        self.__sorted = False

    def get(self, injector):
        if not self.__sorted:
            self._sort_providers()
       return super().get(injector)

    def _sort_providers(self):
        # not thread safe
        self._providers = sorted(self._providers, key=self.__ordering)
```

But since multibind hard codes its uses of MultiBindProvider and MapBindProvider it's impossible to supply a custom implementation of ListOfProviders (well...not impossible, just gross) and supplying the customized provider to multibind itself would only cause that particular chunk to be prioritized at resolution.

Thoughts? Did I overlook something or is this a potential addition to this library?

**Comment by alecthomas** [comment]
I think this is best handled by having the consumer do the sorting by priority.

**Comment by justanr** [comment]
I'm not sure that would work since that'd require each resolved item to know its priority, unless I'm misunderstanding you. Are you saying something like:

```python
class Receiver:
    @inject
    def __init__(self, auth_handlers: AuthHandler) -> None:
        self._auth_handlers = determine_auth_order(auth_handler)
```

**Comment by alecthomas** [comment]
Yes, something like:

```python
class AuthenticationHandler(ABC):
    @abstractproperty
    def priority(self): pass

    def authenticate(self, identifier: str, secret: str) -> Optional[User]:
        pass


def authentiation_handlers(handlers: AuthenticationHandlers):
    handlers = sort(handlers, key=lambda h: h.priority)
```

This is basically the same amount of work.
