### ISSUE TITLE
Remove setuptools from dependencies

### ISSUE THREAD

**Issue by pohmelie** [alecthomas/injector#83]
Package itself do not use `setuptools` and should not be in `install_requires` section. Solutions:
* Move `setuptools` from `install_requires` to `setup_requires` (which is available since [0.6a1](https://setuptools.readthedocs.io/en/latest/history.html#a1))
* Drop `setuptools` requirement at all, since your version requirement for `setuptools` is `0.6b1` and this version was released almost 10 years(!) ago, I hope no one use it nowadays.

Why this counts for us. We build debian packages from python packages and since modern python have `setuptools` bundled, we do not need to build debian package of setuptools, but since this dependency in `injector` we have to.

**Comment by alecthomas** [comment]
Sounds reasonable. I'd happily merge a PR.

**Comment by pohmelie** [comment]
@alecthomas 
Which solution you prefer?

**Comment by alecthomas** [comment]
Drop it!
